"""Web frontend for the customer-support cascade agent.

One text pipeline — sanitize -> A2A Security Judge -> ADK agent (+ MCP tools, Mem0) ->
A2A Data Masker — exposed three ways from this FastAPI app:

  * ``POST /api/chat``         one JSON reply (used by scripts / the benchmark)
  * ``POST /api/chat/stream``  the same turn as newline-delimited JSON *events*: every
                               pipeline step, each with its type, latency, Phoenix span,
                               the SQL an MCP tool ran, Gemini's decision and tokens
  * ``/voice/ws``              the voice cascade (cs_agent/voice/router.py): STT, then
                               this exact pipeline, then TTS — emitting the same events

The single-page UI (cs_agent/static/index.html) renders those events as a "What happened"
panel under every answer, and ``/architecture`` lights up the system diagram live.

Run it via:  ./run.sh web      (or: python -m cs_agent.web)
Requires the same services as the CLI: Postgres, MCP Toolbox (:5000), A2A (:10002/:10003).
"""

import warnings
warnings.filterwarnings("ignore")
warnings.showwarning = lambda *a, **k: None

import json
import logging
import os
import sys
import time
import urllib.request

logging.getLogger().setLevel(logging.ERROR)

_this_dir = os.path.dirname(os.path.abspath(__file__))
_project_root = os.path.dirname(_this_dir)
for p in (_this_dir, _project_root):
    if p not in sys.path:
        sys.path.insert(0, p)

import yaml
from dotenv import load_dotenv
from fastapi import FastAPI
from fastapi.responses import FileResponse, JSONResponse, StreamingResponse
from pydantic import BaseModel
from google.genai import types
from google.adk.agents.llm_agent import LlmAgent
from google.adk.agents.run_config import RunConfig, StreamingMode
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from toolbox_core import ToolboxSyncClient

from memory import search_memory, save_memory
from prompts import SQL_PROMPT_INSTRUCTION
from greet import authenticate_user
from cs_agent.security.sanitizer import sanitize_input
from cs_agent.a2a.client import call_a2a_agent
from telemetry import get_tracer, ATTR, telemetry_enabled

load_dotenv()
os.environ.pop("GOOGLE_GENAI_USE_VERTEXAI", None)

# Observability (Phoenix). No-op unless TELEMETRY=true — see telemetry.py / .env.
tracer = get_tracer()

# Cascade profile — hard-coded ports (kept distinct from the s2s app so both can run
# at once). A2A Judge/Mask, the MCP Toolbox this app talks to, and Phoenix.
A2A_JUDGE_HOST = "localhost"
A2A_JUDGE_PORT = 10002
A2A_MASK_HOST = "localhost"
A2A_MASK_PORT = 10003
TOOLBOX_URL = "http://127.0.0.1:5000"
PHOENIX_URL = "http://localhost:6006"
AGENT_MODEL = "gemini-2.5-flash"

toolbox_client = ToolboxSyncClient(url=TOOLBOX_URL)
database_tools = toolbox_client.load_toolset("cs_agent_tools")

_STATIC = os.path.join(_this_dir, "static")


# --- What each tool *is* (shown in the UI next to every call) ----------------------
def _tool_catalogue() -> dict:
    """MCP tools from mcp_toolbox/tools.yaml: kind, READ/WRITE, the SQL, its params."""
    path = os.path.join(_project_root, "mcp_toolbox", "tools.yaml")
    try:
        with open(path) as f:
            cfg = yaml.safe_load(f)
    except OSError:          # generated by `./run.sh setup`; UI degrades to a plain row
        return {}
    out = {}
    for name, t in cfg["tools"].items():
        stmt = t.get("statement", "").strip()
        out[name] = {
            "kind": "MCP",
            "access": "READ" if stmt.upper().startswith("SELECT") else "WRITE",
            "path": ["Gemini function call", "ADK", "toolbox-core", "MCP tools/call",
                     "Toolbox :5000", "PostgreSQL"],
            "runs": f"{t['kind']} on {t['source']}",
            "statement": stmt,
            "params": [p["name"] for p in t.get("parameters", [])],
        }
    return out


TOOLS = _tool_catalogue()
TOOLS["search_memory"] = {
    "kind": "Python fn",
    "access": "READ",
    "path": ["Gemini function call", "ADK", "search_memory()", "mem0.search()", "Mem0 cloud API"],
    "runs": "cs_agent/memory.py — the agent decides when to recall; results come back as tool output",
}


def tool_info(name: str) -> dict:
    return TOOLS.get(name, {"kind": "tool"})


# --- Phoenix deep link for a trace ---------------------------------------------------
_phoenix_project = None


def trace_url(span) -> dict | None:
    """{trace_id, url} for a real OTel span; None when telemetry is off (no-op span)."""
    if not telemetry_enabled() or not hasattr(span, "get_span_context"):
        return None
    global _phoenix_project
    trace_id = format(span.get_span_context().trace_id, "032x")
    if _phoenix_project is None:
        try:
            with urllib.request.urlopen(f"{PHOENIX_URL}/v1/projects", timeout=2) as r:
                projects = json.load(r)["data"]
            _phoenix_project = next(p["id"] for p in projects if p["name"] == "default")
        except Exception:
            return {"trace_id": trace_id, "url": f"{PHOENIX_URL}/projects"}
    return {"trace_id": trace_id, "url": f"{PHOENIX_URL}/projects/{_phoenix_project}/traces/{trace_id}"}


session_service = InMemorySessionService()
_runners: dict[str, Runner] = {}   # user_id -> Runner
_transcripts: dict[str, list] = {}  # user_id -> running [{role, content}] for this session,
                                    # flushed to Mem0 on logout (mirrors the CLI's save-on-quit)


def _record(user_id: str, role: str, content: str) -> None:
    """Append one message to this user's session transcript (persisted on logout)."""
    if user_id and content:
        _transcripts.setdefault(user_id, []).append({"role": role, "content": content})


app = FastAPI(title="Customer Support Agent")


class LoginReq(BaseModel):
    email: str
    password: str


class ChatReq(BaseModel):
    user_id: str
    message: str


class LogoutReq(BaseModel):
    user_id: str


def _build_runner(user_id: str) -> Runner:
    agent = LlmAgent(
        model=AGENT_MODEL,
        name="customer_support_assistant",
        description="Customer support agent for order questions and requests.",
        instruction=SQL_PROMPT_INSTRUCTION.format(USER_ID=user_id),
        tools=[*database_tools, search_memory],
    )
    return Runner(agent=agent, app_name="agents", session_service=session_service)


async def _judge(text: str) -> tuple[bool, str]:
    """(cleared, verdict) from the Security Judge."""
    verdict = await call_a2a_agent(query=text, host=A2A_JUDGE_HOST, port=A2A_JUDGE_PORT) or ""
    return "BLOCKED" not in verdict.upper(), verdict


# MASK=false skips the A2A Masker entirely (no round-trip, no latency). Default true.
MASK_ENABLED = os.getenv("MASK", "true").strip().lower() in ("1", "true", "yes", "on")


async def _mask(text: str) -> tuple[str, str]:
    """(masked text, human-readable note)."""
    try:
        masked = await call_a2a_agent(query=text, host=A2A_MASK_HOST, port=A2A_MASK_PORT)
    except Exception as exc:
        return text, f"Masker unreachable, response sent unmasked ({exc})"
    out = masked or text
    note = "no PII found, response unchanged" if out.strip() == text.strip() else "PII masked in the response"
    return out, note


@app.post("/api/login")
async def login(req: LoginReq):
    ctx = authenticate_user(email=req.email, password=req.password)
    if not ctx:
        return JSONResponse({"ok": False, "error": "Invalid email or password."}, status_code=401)
    uid = ctx["email"]
    _runners[uid] = _build_runner(uid)
    _transcripts[uid] = []            # fresh session transcript (drop any stale unsaved buffer)
    sid = f"session_{uid}"
    # Make login idempotent — a repeat login (or page reload) must not 500 on a
    # session id that already exists. Recreate it fresh.
    try:
        await session_service.delete_session(app_name="agents", user_id=uid, session_id=sid)
    except Exception:
        pass
    await session_service.create_session(app_name="agents", user_id=uid, session_id=sid)
    return {
        "ok": True,
        "user_id": uid,
        "full_name": ctx.get("full_name"),
        "is_premium": bool(ctx.get("is_premium_customer")),
        "items": ctx.get("total_items_purchased", 0),
    }


@app.post("/api/logout")
async def logout(req: LogoutReq):
    _runners.pop(req.user_id, None)
    # Persist this session's conversation to Mem0 — the web equivalent of the CLI's
    # save_memory(...) on `quit`. Fired by the Sign-out button AND by the browser tab
    # closing (sendBeacon -> /api/logout). pop() makes it save-once even if both fire.
    messages = _transcripts.pop(req.user_id, None)
    if messages:
        try:
            save_memory(messages, req.user_id)
        except Exception:
            pass
    try:
        await session_service.delete_session(
            app_name="agents", user_id=req.user_id, session_id=f"session_{req.user_id}")
    except Exception:
        pass
    return {"ok": True}


# --- The pipeline, as a stream of events -------------------------------------------
def _ms(t0: float) -> int:
    return int((time.perf_counter() - t0) * 1000)


def _decode(value):
    if isinstance(value, str) and value.lstrip()[:1] in ("{", "["):
        try:
            return json.loads(value)
        except ValueError:
            pass
    return value


def _unwrap(resp):
    """Toolbox returns {"result": "<json string>"}; show the rows, not the envelope."""
    if isinstance(resp, dict) and set(resp) == {"result"}:
        resp = resp["result"]
    if isinstance(resp, str):
        try:
            return json.loads(resp)
        except ValueError:
            return resp
    return resp


def _step(key, title, ok, detail, span, t0, **extra):
    return dict(type="step", key=key, title=title, status="passed" if ok else "blocked",
                detail=detail, span=span, ms=_ms(t0), **extra)


async def text_pipeline(runner, user_id: str, text: str, *, stream: bool = False,
                        turn_span=None, mask: bool | None = None):
    """Run one turn and yield pipeline events (dicts).

    Event types (the UI renders each as a row in "What happened"):
      stage        a step is starting                {key, stage}
      step         a step finished                   {key, title, status, detail, span, ms, kind, runs}
      llm          one Gemini call by the agent      {model, detail, tokens_in, tokens_out, ms, span}
      tool_call    the agent called a tool           {id, name, args, info, span}
      tool_result  ...and got its result             {id, name, result, ms}
      delta        streamed partial reply (cumulative text) — only when stream=True
      final        the reply                         {blocked, stage?, response}

    ``stream`` streams the agent's text as it is generated (SSE) and *skips the Masker*:
    you cannot mask a reply you are already showing. ``mask`` overrides MASK for this
    turn (the voice router uses this).

    Spans: the caller owns the enclosing turn span (``agent.turn`` for text,
    ``voice.turn`` for voice) and passes it in so this can mark it blocked / set its output.
    """
    do_mask = MASK_ENABLED if mask is None else mask

    def blocked(stage, msg):
        if turn_span is not None:
            turn_span.set_attribute("turn.blocked", True)
            turn_span.set_attribute("turn.block_reason", stage)
            turn_span.set_attribute(ATTR.OUTPUT_VALUE, f"BLOCKED: {stage}")
        return dict(type="final", blocked=True, stage=stage, response=msg)

    # Layer 1 — local sanitization
    yield dict(type="stage", key="sanitize", stage="Sanitizing input")
    t0 = time.perf_counter()
    with tracer.start_as_current_span("security.sanitize") as span:
        span.set_attribute(ATTR.OPENINFERENCE_SPAN_KIND, "GUARDRAIL")
        span.set_attribute(ATTR.INPUT_VALUE, text[:500])
        try:
            clean = sanitize_input(text)
            span.set_attribute(ATTR.OUTPUT_VALUE, "passed")
            reason = "length and character checks passed, no blocked patterns"
        except ValueError as exc:
            reason = str(exc)
            span.set_attribute(ATTR.OUTPUT_VALUE, f"blocked: {reason}")
            clean = None
    yield _step("sanitize", "Sanitizer", clean is not None, reason, "security.sanitize", t0,
                kind="in-process", runs="regex blocklist in cs_agent/security/sanitizer.py")
    if clean is None:
        yield blocked("sanitizer", f"Input rejected by sanitizer: {reason}")
        return

    # Layer 2 — A2A Security Judge
    yield dict(type="stage", key="judge", stage="A2A Security Judge")
    t0 = time.perf_counter()
    with tracer.start_as_current_span("security.a2a_judge") as span:
        span.set_attribute(ATTR.OPENINFERENCE_SPAN_KIND, "GUARDRAIL")
        span.set_attribute(ATTR.INPUT_VALUE, clean)
        try:
            ok, verdict = await _judge(clean)
        except Exception as exc:
            span.set_attribute(ATTR.OUTPUT_VALUE, f"error: {exc}")
            yield dict(type="error", error=f"Security Judge unreachable: {exc}")
            return
        span.set_attribute(ATTR.OUTPUT_VALUE, "passed" if ok else "blocked")
    judged = ("cleared: echoed the input back unmodified, its signal for safe "
              "(regex evaluator tool + Gemini found no injection)"
              if ok else f"returned BLOCKED: {verdict.strip()[:200]}")
    yield _step("judge", "Security Judge", ok, judged, "security.a2a_judge", t0,
                kind="A2A", runs=f"ADK agent behind an A2A server at :{A2A_JUDGE_PORT}",
                text_chars=len(clean))
    if not ok:
        yield blocked("judge", "Blocked by the A2A Security Judge (possible injection/unsafe input).")
        return

    # Agent turn (+ MCP tools, Mem0 via the search_memory tool)
    yield dict(type="stage", key="agent", stage="Agent thinking")
    content = types.Content(role="user", parts=[types.Part(text=clean)])
    run_config = RunConfig(streaming_mode=StreamingMode.SSE) if stream else None
    final_text, display, n, t0 = "", "", 0, time.perf_counter()
    pending: dict[str, list[tuple[int, float, dict]]] = {}
    seen_partial = False
    async for event in runner.run_async(user_id=user_id, session_id=f"session_{user_id}",
                                        new_message=content, run_config=run_config):
        partial = bool(getattr(event, "partial", False))
        # SSE surfaces the SAME function call on the partial and the final event — read
        # tool calls/results (and usage) on non-partial events only, or they double-count.
        calls = [] if partial else (event.get_function_calls() or [])
        if not partial and event.author != "user" and event.content and (calls or event.is_final_response()):
            u = event.usage_metadata
            decided = (f"decided to call {', '.join(c.name for c in calls)}" if calls
                       else "wrote the final answer")
            yield dict(type="llm", title="Gemini", detail=decided, span="call_llm",
                       model=AGENT_MODEL, ms=_ms(t0),
                       tokens_in=getattr(u, "prompt_token_count", None),
                       tokens_out=getattr(u, "candidates_token_count", None))
        for fc in calls:
            n += 1
            args = {k: _decode(v) for k, v in (fc.args or {}).items()}
            pending.setdefault(fc.name, []).append((n, time.perf_counter(), args))
            yield dict(type="tool_call", id=n, name=fc.name, span=f"tool.{fc.name}",
                       info=tool_info(fc.name), args=args)
        for fr in ([] if partial else (event.get_function_responses() or [])):
            tid, started, args = (pending.get(fr.name) or [(None, time.perf_counter(), {})]).pop(0)
            result = _unwrap(fr.response)
            with tracer.start_as_current_span(f"tool.{fr.name}") as span:
                span.set_attribute(ATTR.OPENINFERENCE_SPAN_KIND, "TOOL")
                span.set_attribute(ATTR.TOOL_NAME, fr.name)
                span.set_attribute(ATTR.INPUT_VALUE, json.dumps(args, default=str))
                span.set_attribute(ATTR.OUTPUT_VALUE, json.dumps(result, default=str)[:2000])
            yield dict(type="tool_result", id=tid, name=fr.name, ms=_ms(started), result=result)
            yield dict(type="stage", key="agent", stage="Agent thinking")
            t0 = time.perf_counter()
        txt = event.content.parts[0].text if (event.content and event.content.parts) else None
        if stream and txt:
            if partial:
                seen_partial = True
            elif seen_partial:
                continue          # redundant final aggregate that repeats the partials
            display += txt
            yield dict(type="delta", text=display)
        if event.is_final_response() and event.content and event.content.parts:
            final_text = event.content.parts[0].text or ""
    if stream:
        final_text = display or final_text

    # Layer 3 — A2A Data Masker on the way out (never when streaming: the text is out)
    if do_mask and not stream:
        yield dict(type="stage", key="mask", stage="A2A Data Masker")
        t0 = time.perf_counter()
        with tracer.start_as_current_span("security.a2a_mask") as span:
            span.set_attribute(ATTR.OPENINFERENCE_SPAN_KIND, "GUARDRAIL")
            span.set_attribute(ATTR.INPUT_VALUE, final_text[:500])
            masked, note = await _mask(final_text)
            span.set_attribute(ATTR.OUTPUT_VALUE, masked[:500])
        yield _step("mask", "Data Masker", True, note, "security.a2a_mask", t0,
                    kind="A2A", runs=f"ADK agent behind an A2A server at :{A2A_MASK_PORT}",
                    in_chars=len(final_text), out_chars=len(masked))
        final_text = masked

    if turn_span is not None:
        turn_span.set_attribute(ATTR.OUTPUT_VALUE, final_text)
    yield dict(type="final", blocked=False, response=final_text)


def _turn_span(user_id: str, message: str, channel: str):
    turn = tracer.start_as_current_span("agent.turn")
    span = turn.__enter__()
    span.set_attribute(ATTR.OPENINFERENCE_SPAN_KIND, "CHAIN")
    span.set_attribute(ATTR.INPUT_VALUE, message)
    span.set_attribute("user.id", user_id)
    span.set_attribute("turn.channel", channel)
    return turn, span


@app.post("/api/chat")
async def chat(req: ChatReq):
    """One JSON reply: {ok, blocked, stage?, response, tool_calls}."""
    runner = _runners.get(req.user_id)
    if runner is None:
        return JSONResponse({"ok": False, "error": "Not logged in."}, status_code=401)
    turn, span = _turn_span(req.user_id, req.message, "text")
    tool_calls, out = [], None
    try:
        async for e in text_pipeline(runner, req.user_id, req.message, turn_span=span):
            if e["type"] == "tool_call":
                tool_calls.append({"name": e["name"], "args": e["args"], "result": None})
            elif e["type"] == "tool_result":
                for tc in reversed(tool_calls):
                    if tc["name"] == e["name"] and tc["result"] is None:
                        tc["result"] = json.dumps(e["result"], default=str)[:800]
                        break
            elif e["type"] == "error":
                return JSONResponse({"ok": False, "error": e["error"]}, status_code=502)
            elif e["type"] == "final":
                out = e
    finally:
        turn.__exit__(None, None, None)
    if out["blocked"]:
        return {"ok": True, "blocked": True, "stage": out["stage"], "response": out["response"], "tool_calls": []}
    _record(req.user_id, "user", req.message)
    _record(req.user_id, "assistant", out["response"])
    return {"ok": True, "blocked": False, "response": out["response"], "tool_calls": tool_calls}


@app.post("/api/chat/stream")
async def chat_stream(req: ChatReq):
    """Same pipeline, as newline-delimited JSON events (see text_pipeline).

    The reply streams token by token only when MASK is off — a reply that must be
    masked as a whole can't be shown before the Masker has seen it.
    """
    runner = _runners.get(req.user_id)
    if runner is None:
        return JSONResponse({"ok": False, "error": "Not logged in."}, status_code=401)

    async def gen():
        turn, span = _turn_span(req.user_id, req.message, "text-stream")
        try:
            t = trace_url(span)
            if t:
                yield json.dumps(dict(type="trace", span="agent.turn", **t)) + "\n"
            async for e in text_pipeline(runner, req.user_id, req.message,
                                         stream=not MASK_ENABLED, turn_span=span):
                yield json.dumps(e, default=str) + "\n"
                if e["type"] == "final" and not e["blocked"]:
                    _record(req.user_id, "user", req.message)
                    _record(req.user_id, "assistant", e["response"])
        finally:
            turn.__exit__(None, None, None)

    return StreamingResponse(gen(), media_type="application/x-ndjson")


# Voice cascade (STT -> text_pipeline -> TTS) — all logic lives in cs_agent/voice/;
# we hand it the pipeline and the shared session objects.
from cs_agent.voice.router import make_voice_router
app.include_router(make_voice_router(
    runners=_runners, pipeline=text_pipeline, record=_record, trace_url=trace_url,
    mask_enabled=MASK_ENABLED))


@app.get("/")
def index():
    return FileResponse(os.path.join(_STATIC, "index.html"), media_type="text/html")


@app.get("/architecture")
def architecture_page():
    return FileResponse(os.path.join(_STATIC, "architecture.html"), media_type="text/html")


@app.get("/architecture.svg")
def architecture_svg():
    return FileResponse(os.path.join(_STATIC, "architecture.svg"), media_type="image/svg+xml")


def main():
    import uvicorn
    from cs_agent.voice.router import print_config_warnings
    host = "127.0.0.1"
    port = 8000                       # cascade profile (s2s uses 8001)
    print(f"Customer Support web UI -> http://{host}:{port}   (architecture: http://{host}:{port}/architecture)")
    print_config_warnings()
    uvicorn.run(app, host=host, port=port, log_level="warning")


if __name__ == "__main__":
    main()
