"""Speech-to-speech (voice) web app for the customer-support agent.

A FastAPI app on its own port (8001) that wires a browser WebSocket to the Gemini Live
voice engine in ``cs_agent/voice.py`` and reuses the shared building blocks (auth, MCP
tools, Mem0, prompts, A2A client). The text CLI (``agent_cli.py``) is untouched.

The single-page UI (cs_agent/static/index.html + static/voice.js) renders every event the
engine emits — the post-hoc Security Judge, each tool call with the SQL it ran, the Live
model's tokens, the Phoenix trace — as a "What happened" panel under each spoken or typed
answer, and ``/architecture`` lights up the system diagram live.

Run it:  ./run.sh voice        (or: python -m cs_agent.web)
Needs: Postgres (:5433), MCP Toolbox (:5001), A2A (:11002/:11003), plus a GOOGLE_API_KEY
whose project has access to the Gemini Live model (see voice.py:VOICE_MODEL).

Browser note: microphone capture requires a secure context — http://127.0.0.1 / localhost
qualifies; a bare LAN IP over http does not (browsers block getUserMedia there).
"""

import warnings
warnings.filterwarnings("ignore")
warnings.showwarning = lambda *a, **k: None

import json
import logging
import os
import sys
import urllib.request

logging.getLogger().setLevel(logging.ERROR)

_this_dir = os.path.dirname(os.path.abspath(__file__))
_project_root = os.path.dirname(_this_dir)
for p in (_this_dir, _project_root):
    if p not in sys.path:
        sys.path.insert(0, p)

import yaml
from dotenv import load_dotenv
from fastapi import FastAPI, WebSocket
from fastapi.responses import FileResponse, JSONResponse
from pydantic import BaseModel
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from toolbox_core import ToolboxSyncClient

from memory import search_memory, save_memory
from greet import authenticate_user
from cs_agent.voice import make_voice_agent, run_voice_session, VOICE_MODEL, VOICE_NAME
from telemetry import get_tracer, telemetry_enabled

load_dotenv()
os.environ.pop("GOOGLE_GENAI_USE_VERTEXAI", None)

# Observability (Phoenix). No-op unless TELEMETRY=true — see telemetry.py / .env.
# Init here so the Live model calls in voice.py are auto-instrumented for both
# typed and spoken turns (they share this process).
get_tracer()

logger = logging.getLogger(__name__)

# s2s profile — its OWN MCP Toolbox on 5001 and Phoenix on 6007 (cascade: 5000 / 6006),
# so both apps run at once.
TOOLBOX_URL = "http://127.0.0.1:5001"
PHOENIX_URL = "http://localhost:6007"

toolbox_client = ToolboxSyncClient(url=TOOLBOX_URL)
database_tools = toolbox_client.load_toolset("cs_agent_tools")

_STATIC = os.path.join(_this_dir, "static")


# --- What each tool *is* (shown in the UI next to every call) ----------------------
def _tool_catalogue() -> dict:
    """MCP tools from mcp_toolbox/tools.yaml: kind, READ/WRITE, the SQL, its params."""
    path = os.path.join(_project_root, "mcp_toolbox", "tools.yaml")
    try:
        with open(path) as f:
            cfg = yaml.safe_load(f)
    except OSError:          # generated by `./run.sh setup`; UI degrades to a plain row
        return {}
    out = {}
    for name, t in cfg["tools"].items():
        stmt = t.get("statement", "").strip()
        out[name] = {
            "kind": "MCP",
            "access": "READ" if stmt.upper().startswith("SELECT") else "WRITE",
            "path": ["Gemini Live function call", "ADK", "toolbox-core", "MCP tools/call",
                     "Toolbox :5001", "PostgreSQL"],
            "runs": f"{t['kind']} on {t['source']}",
            "statement": stmt,
            "params": [p["name"] for p in t.get("parameters", [])],
        }
    return out


TOOLS = _tool_catalogue()
TOOLS["search_memory"] = {
    "kind": "Python fn",
    "access": "READ",
    "path": ["Gemini Live function call", "ADK", "search_memory()", "mem0.search()", "Mem0 cloud API"],
    "runs": "cs_agent/memory.py — the agent decides when to recall; results come back as tool output",
}


def tool_info(name: str) -> dict:
    return TOOLS.get(name, {"kind": "tool"})


# --- Phoenix deep link for a trace ---------------------------------------------------
_phoenix_project = None


def trace_url(span) -> dict | None:
    """{trace_id, url} for a real OTel span; None when telemetry is off (no-op span)."""
    if not telemetry_enabled() or not hasattr(span, "get_span_context"):
        return None
    global _phoenix_project
    trace_id = format(span.get_span_context().trace_id, "032x")
    if _phoenix_project is None:
        try:
            with urllib.request.urlopen(f"{PHOENIX_URL}/v1/projects", timeout=2) as r:
                projects = json.load(r)["data"]
            _phoenix_project = next(p["id"] for p in projects if p["name"] == "default")
        except Exception:
            return {"trace_id": trace_id, "url": f"{PHOENIX_URL}/projects"}
    return {"trace_id": trace_id, "url": f"{PHOENIX_URL}/projects/{_phoenix_project}/traces/{trace_id}"}


session_service = InMemorySessionService()
_runners: dict[str, Runner] = {}   # user_id -> Runner (Live model)
_transcripts: dict[str, list] = {}  # user_id -> running [{role, content}] for this session,
                                    # flushed to Mem0 on logout (mirrors the CLI's save-on-quit)


def _record(user_id: str, role: str, content: str) -> None:
    """Append one message to this user's session transcript (persisted on logout)."""
    if user_id and content:
        _transcripts.setdefault(user_id, []).append({"role": role, "content": content})


app = FastAPI(title="Customer Support Voice Agent")


class LoginReq(BaseModel):
    email: str
    password: str


class LogoutReq(BaseModel):
    user_id: str


def _build_runner(user_id: str) -> Runner:
    agent = make_voice_agent(user_id, [*database_tools, search_memory])
    return Runner(agent=agent, app_name="voice_agents", session_service=session_service)


@app.post("/api/login")
async def login(req: LoginReq):
    ctx = authenticate_user(email=req.email, password=req.password)
    if not ctx:
        return JSONResponse({"ok": False, "error": "Invalid email or password."}, status_code=401)
    uid = ctx["email"]
    _runners[uid] = _build_runner(uid)
    _transcripts[uid] = []            # fresh session transcript (drop any stale unsaved buffer)
    return {
        "ok": True,
        "user_id": uid,
        "full_name": ctx.get("full_name"),
        "is_premium": bool(ctx.get("is_premium_customer")),
        "items": ctx.get("total_items_purchased", 0),
        "model": VOICE_MODEL,
        "voice": VOICE_NAME,
    }


@app.post("/api/logout")
async def logout(req: LogoutReq):
    _runners.pop(req.user_id, None)
    # Persist this session's conversation to Mem0 — the web equivalent of the CLI's
    # save_memory(...) on `quit`. Fired by the Sign-out button AND by the browser tab
    # closing (sendBeacon -> /api/logout). pop() makes it save-once even if both fire.
    messages = _transcripts.pop(req.user_id, None)
    if messages:
        try:
            save_memory(messages, req.user_id)
        except Exception:
            pass
    try:
        await session_service.delete_session(
            app_name="voice_agents", user_id=req.user_id, session_id=f"voice_{req.user_id}")
    except Exception:
        pass
    return {"ok": True}


@app.websocket("/api/voice")
async def voice_ws(websocket: WebSocket):
    await websocket.accept()
    user_id = websocket.query_params.get("user_id", "")
    runner = _runners.get(user_id)
    if runner is None:
        await websocket.send_json({"type": "error", "text": "Not logged in. Sign in first."})
        await websocket.close()
        return

    session_id = f"voice_{user_id}"
    # Fresh session per connection so a reconnect/reload doesn't 500 on a dup id.
    try:
        await session_service.delete_session(
            app_name="voice_agents", user_id=user_id, session_id=session_id)
    except Exception:
        pass
    await session_service.create_session(
        app_name="voice_agents", user_id=user_id, session_id=session_id)

    await websocket.send_json({"type": "ready"})
    try:
        await run_voice_session(websocket, runner, user_id, session_id, record=_record,
                                tool_info=tool_info, trace_url=trace_url)
    except Exception as exc:  # noqa: BLE001
        logger.exception("voice_ws error: %s", exc)
    finally:
        try:
            await websocket.close()
        except Exception:
            pass


@app.get("/")
def index():
    return FileResponse(os.path.join(_STATIC, "index.html"), media_type="text/html")


@app.get("/static/voice.js", include_in_schema=False)
def voice_js():
    return FileResponse(os.path.join(_STATIC, "voice.js"), media_type="application/javascript")


@app.get("/architecture")
def architecture_page():
    return FileResponse(os.path.join(_STATIC, "architecture.html"), media_type="text/html")


@app.get("/architecture.svg")
def architecture_svg():
    return FileResponse(os.path.join(_STATIC, "architecture.svg"), media_type="image/svg+xml")


def main():
    import uvicorn
    host = "127.0.0.1"
    port = 8001                       # s2s profile (cascade uses 8000)
    print(f"Customer Support VOICE UI -> http://{host}:{port}  (model: {VOICE_MODEL}, voice: {VOICE_NAME})"
          f"   architecture: http://{host}:{port}/architecture")
    uvicorn.run(app, host=host, port=port, log_level="warning")


if __name__ == "__main__":
    main()
